server:
  port: 9991

spring:
  application:
    name: xmopay-demo
  freemarker:
    allow-request-override: false
    cache: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html; charset=utf-8
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    #模板加载的位置
    template-loader-path: classpath:/templates/
    #后缀
    suffix: .ftl
    settings:
      locale: zh_CN
      date_format: yyyy-MM-dd
      time_format: HH:mm:ss
      datetime_format: yyyy-MM-dd HH:mm:ss
      number_format: 0.##
  jackson:
    time-zone: GMT+8
  resources:
    static-locations: classpath:/static/**

logs:
  path: ./logs
  level: info